### ISSUE TITLE
Super buen trabajo!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-AiaRup#1]
Buen trabajo @AiaRup !

Algunas pistas para mejorarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Haz que el filtrado funcione con mayúsculas o minúsculas ;)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by AiaRup** [comment]
Hola carlos, Muchas gracias! He terminado todas las cosas que escribiste. No agregué nada sorprendente, porque prefiero trabajar en mi portfolio 😉

**Comment by oneeyedman** [comment]
@AiaRup, excelente trabajo y buena elección dedicar esfuerzos a tu portfolio.
